### ISSUE TITLE
Task Disappears

### ISSUE THREAD

**Issue by xesunny** [googleapis/nodejs-tasks#424]
We built an app that heavily rely on google cloud task, but as our user base is increasing we are pushing 100s of cloud task in a queue. While 99%+ of task gets executed correctly, there are few that just disappear. 

It's a very strange issue. Having no logs adds salt to injury. I added custom logs in my application to print task name.

My application A --> create cloud tasks --> calls another application B

A creates CT successfully but B receives 99%+ tasks only, not 100%.

Example this ask: 
locations/asia-south1/queues/tpl-pending/tasks/88947425534926389671

**Comment by bcoe** [comment]
@xesunny thanks for the bug report 👍 

It sounds like this is most likely related to the service/API itself (vs., the client library). It would be worth opening an issue on the product as well:

https://issuetracker.google.com/savedsearches/5433985

**Comment by averikitsch** [comment]
Please file an issue because Cloud Tasks guarantees at least once delivery. Though I would also make sure you are not adding duplicated tasks (named tasks) since those will be de-duplicated, scheduling tasks too close to the task creation time, and checking your queue retry settings (if a tasks fails too many times then it will disappear from the queue).

**Comment by averikitsch** [comment]
Stale issue. Please reopen if necessary.
