### ISSUE TITLE
Filter listTask

### ISSUE THREAD

**Issue by aarifkhamdi** [googleapis/nodejs-tasks#585]
I want to update task some way. I can't delete and create new task because I can't reuse task name for some period. So I have to search for a task, delete previous task and create new one with new name. For example, my task name would be "task1", "task2"... But I have to fetch all the tasks in queue. It would be much better to search for "task" to find my task. In GCP console there is ability to filter tasks. But I can't filter through API.

**Comment by averikitsch** [comment]
Hi @aarifkhamdi, since tasks are mostly ephemeral (not scheduled), we don't provide a method to update tasks. Naming a task is aimed at deduplicating tasks. Like you mentioned, you can not create a task with the same name. Task naming can also be Task names can be autogenerated if you don't specify a name; therefore you would not have to worry about updating the name. 

Naming tasks can be helpful as you mentioned to filter tasks. You can get a single task with [`getTask`](https://cloud.google.com/nodejs/docs/reference/tasks/latest/tasks/v2.cloudtasksclient#_google_cloud_tasks_v2_CloudTasksClient_getTask_member_1_).

Please add more info on your use case for further help.
